### PR TITLE
Enhance Turnstile Captcha Integration

### PR DESCRIPTION
**Pull request by trinib**
# Enhance Turnstile Captcha Integration

- Added configuration options for Captcha theme and size.
- Improved Captcha verification process with error logging and redirection.
- Updated error message display.
- Included new page type for password resets.
- Refactored JavaScript for better Captcha widget integration and error handling.

image

## Changes Overview

Updated Configuration Constants:

- Added HYBULA_TURNSTILE_SIZE: Controls the size of the Turnstile widget (e.g., normal, compact).
- Changed HYBULA_TURNSTILE_THEME: Updated from 'auto' to 'dark' to set a specific visual theme.
- Added HYBULA_TURNSTILE_LOCATIONS: Now includes a new page type for password reset.
- Updated HYBULA_TURNSTILE_ERROR: Changed error message display format to be more visible.

Refactored Captcha Verification Process:

- Added sanitize_input() Function: Ensures that input data is clean and secure.
- Added verify_turnstile() Function: Separates the Turnstile verification logic into its own function for better organization and error handling.
- Updated Captcha Validation Logic: Improved the logic to check various page types, including password reset. If Captcha verification fails, the user is redirected to the same page with an error message.

Updated Captcha Integration into Pages:

- Refactored JavaScript Code: Added error message handling directly in the script. Also, the Turnstile widget configuration is updated to include size and theme options.

## Detailed Breakdown

<b>1. Configuration Changes</b>

Constants Updated:

- HYBULA_TURNSTILE_ENABLED: Whether Turnstile is active (remains true).
- HYBULA_TURNSTILE_CREDITS: Whether to show credits for the integration (remains true).
- HYBULA_TURNSTILE_EXCLUDE_LOGIN: Whether to exclude login pages (remains true).
- HYBULA_TURNSTILE_SITE: Turnstile site key (unchanged).
- HYBULA_TURNSTILE_SECRET: Turnstile secret key (unchanged).
- HYBULA_TURNSTILE_THEME: Changed from 'auto' to 'dark' for a consistent theme.
- HYBULA_TURNSTILE_SIZE: New constant to control the size of the Turnstile widget.
- HYBULA_TURNSTILE_LOCATIONS: Added 'passwordreset' for password reset pages.
- HYBULA_TURNSTILE_ERROR: Updated error message styling to be more visible.

<b>2. Captcha Verification Enhancements</b>

- Sanitize Input: Ensures input data is safe from special characters that could be used for attacks.
- Verify Turnstile: Encapsulates the Captcha verification process in a function for clarity. Logs errors and checks the success of the Captcha verification.
- Redirection on Failure: If Captcha fails, the user is redirected back to the same page with an error message.

<b>3. Script Changes for Captcha Integration</b>

- Error Message Handling: Adds a div for error messages directly in the JavaScript code. The message is styled to stand out if verification fails.
- Dynamic Captcha Widget: Configures the Turnstile widget based on the defined theme and size. Inserts it into the form on the page if required.

### CODE REVIEW

**Comment by trinib** [comment]
@dqos can take a look at this and if you think its better . please merge . thanks for this btw !!!! ❤

**Comment by dqos** [comment]
> @dqos can take a look at this and if you think its better . please merge . thanks for this btw !!!! ❤

Thank you for your effort. I will review this asap, with most things I agree but there are some caveats.

Another user reported an issue, the captcha works fine on Order Checkout, however there is also a Login form on the same page. When you try to login, the script blocks it because no captcha data is sent in this form. So we need to implement form IDs (for multiple captchas on a page) and process that. See the attachment, do you have suggestions? I couldn't find anything in Turnstile docs about this.

image

**Comment by trinib** [comment]
@dqos I fixed the login hang but I cannot get the AI(gpt/mistral/claude) to make CAPTCHA work with it. I get it to show with login button but only logs in without verification and can't get it to work to otherwise. 
In WHMCS default CAPTCHAs don't even work with login button on cart/checkout page. 
I also tried asking AI to make separate hook for server side detection and adding CAPTCHA client side to checkout.tpl file login from field and still logging in without verification. 
I don't know if you want it like that if it worked, for I have not dive deeper with AI with that method , I mean I tried a few times until it said to create php file and shit and need to apply permission through CMD to new file . So if you want to explore that which I feel you would not for it just makes things more complicated, you can try.

---
@trinib
[Fixed checkout login button hang(please wait)](https://github.com/hybula/whmcs-turnstile/pull/10/commits/b5f6e4cdf9767916f01cb3be4433d8ebe725c740)
## Here is a breakdown of changes

### Original Logic

In the original script, the logic for detecting a login page was simpler and did not account for the possibility of login forms appearing on pages related to the cart:

```php
$isLoginPage = ($pageFile == 'index' && isset($_POST['username']) && isset($_POST['password']) && in_array('login', HYBULA_TURNSTILE_LOCATIONS));
```

This condition checks if the current page is index.php and if the form data includes username and password, which indicates a login attempt. However, it didn't differentiate between a regular login page and a login form that might appear on the cart or checkout pages.

### Revised Logic

In the revised version, additional checks were introduced to ensure that the CAPTCHA would not be applied on pages where a login form is part of the cart or checkout process:

```php
$isLoginPage = (
    in_array('login', HYBULA_TURNSTILE_LOCATIONS) && 
    (
        // Main login page detection, excluding cart.
        ($pageFile == 'index' && isset($_POST['username']) && isset($_POST['password']) && !strpos($requestUri, '/cart')) ||
        // Specific login form action detection, excluding cart.
        (isset($_POST['action']) && $_POST['action'] == 'login' && !strpos($requestUri, '/cart')) ||
        // Login URL pattern detection, excluding cart.
        (strpos($requestUri, '/login') !== false && !strpos($requestUri, '/cart'))
    )
);
```

### Breakdown of the New Logic

#### Excluding Cart-Related Pages:

- The new logic adds ```!strpos($requestUri, '/cart')``` to each condition, ensuring that if the login form appears on a URL that includes /cart, the CAPTCHA won't be applied. This is important because:
  - Cart Pages: A login prompt on the cart page might be related to a checkout process, where additional steps like CAPTCHA could disrupt the user experience.
  - Checkout Flow: The cart or checkout process should be as smooth as possible, without unnecessary interruptions like CAPTCHA unless absolutely required.

### Expanded Login Detection:

#### The revised logic includes multiple ways to detect a login attempt:
- Page File Check: It still checks if the current page is index.php with username and password fields.
- Form Action Check: It now also checks if a form action is explicitly set to login, which might be used in custom login forms.
- URL Pattern Check: It checks if the URL includes /login, which might indicate a login page, even if the file isn't index.php.

**Comment by trinib** [comment]
@dqos  also you can adjust any caveats and add back your ```<a href="https://github.com/hybula/whmcs-turnstile" target="_blank"><small class="text-muted text-uppercase">Captcha integration by Hybula</small></a>``` signature. 

@trinib OUT ✌️✌️✌️✌️

**Comment by trinib** [comment]
Darn this has an issue with client log in from admin page 😖😩😓😡😠🤬🤢🤮😵🤕🥴😬, lol i see if i get fix

**Comment by trinib** [comment]
fixed error with "login as owner" from admin page
just need to admin path to constant `const HYBULA_ADMIN_PATH = 'YOUR_ADMIN_PATH';`

I just can't get AI make captcha work on login button from cart/checkout page . gave it all the info it needed from turnstile docs and button id and code from checkout.tpl . Maybe its something in WHMCS preventing this🤷‍♂️. I guess just comment out "already registered" button code block from checkout page if its a concern for anyone.

**Pull request closed without merging**
