### PR TITLE
Update hybula_turnstile.php

### PR DESCRIPTION
**Pull request by trinib**
Enhance Turnstile Captcha Integration

- Added configuration options for Captcha theme and size.
- Improved Captcha verification process with error logging and redirection.
- Updated error message display.
- Included new page type for password resets.
- Refactored JavaScript for better Captcha widget integration and error handling.
image

### CODE REVIEW

**Comment by trinib** [comment]
### Changes Overview

**Updated Configuration Constants:**

- Added HYBULA_TURNSTILE_SIZE: Controls the size of the Turnstile widget (e.g., normal, compact).
- Changed HYBULA_TURNSTILE_THEME: Updated from 'auto' to 'dark' to set a specific visual theme.
- Added HYBULA_TURNSTILE_LOCATIONS: Now includes a new page type for password reset.
- Updated HYBULA_TURNSTILE_ERROR: Changed error message display format to be more visible.

**Refactored Captcha Verification Process:**

- Added sanitize_input() Function: Ensures that input data is clean and secure.
- Added verify_turnstile() Function: Separates the Turnstile verification logic into its own function for better organization and error handling.
- Updated Captcha Validation Logic: Improved the logic to check various page types, including password reset. If Captcha verification fails, the user is redirected to the same page with an error message.

**Updated Captcha Integration into Pages:**

- Refactored JavaScript Code: Added error message handling directly in the script. Also, the Turnstile widget configuration is updated to include size and theme options.

### Detailed Breakdown

**1. Configuration Changes**

Constants Updated:

- HYBULA_TURNSTILE_ENABLED: Whether Turnstile is active (remains true).
- HYBULA_TURNSTILE_CREDITS: Whether to show credits for the integration (remains true).
- HYBULA_TURNSTILE_EXCLUDE_LOGIN: Whether to exclude login pages (remains true).
- HYBULA_TURNSTILE_SITE: Turnstile site key (unchanged).
- HYBULA_TURNSTILE_SECRET: Turnstile secret key (unchanged).
- HYBULA_TURNSTILE_THEME: Changed from 'auto' to 'dark' for a consistent theme.
- HYBULA_TURNSTILE_SIZE: New constant to control the size of the Turnstile widget.
- HYBULA_TURNSTILE_LOCATIONS: Added 'passwordreset' for password reset pages.
- HYBULA_TURNSTILE_ERROR: Updated error message styling to be more visible.

**2. Captcha Verification Enhancements**

- Sanitize Input: Ensures input data is safe from special characters that could be used for attacks.
- Verify Turnstile: Encapsulates the Captcha verification process in a function for clarity. Logs errors and checks the success of the Captcha verification.
- Redirection on Failure: If Captcha fails, the user is redirected back to the same page with an error message.

**3. Script Changes for Captcha Integration**

- Error Message Handling: Adds a div for error messages directly in the JavaScript code. The message is styled to stand out if verification fails.
- Dynamic Captcha Widget: Configures the Turnstile widget based on the defined theme and size. Inserts it into the form on the page if required.

**Comment by trinib** [comment]
Updated readme 

Updated installation instuctions
Added a way to work on Admin Login page

**Comment by dqos** [comment]
Thank you for your contribution @trinib, but we are not going to "protect" the `/admin` page using captcha's, please refer to my comment here: https://github.com/hybula/whmcs-turnstile/issues/8#issuecomment-2321482835

Configuration settings must be placed in `configuration.php`, this is the most logical place.

**Comment by trinib** [comment]
> Thank you for your contribution @trinib, but we are not going to "protect" the `/admin` page using captcha's, please refer to my comment here: [#8 (comment)](https://github.com/hybula/whmcs-turnstile/issues/8#issuecomment-2321482835)
> 
> Configuration settings must be placed in `configuration.php`, this is the most logical place.

yes i agree, you can scrap that admin page part .

**Pull request closed without merging**
